### ISSUE TITLE
Overflow-Problem Action-Buttons/Funktionen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/yform_usability#106]
Siehe https://github.com/yakamara/redaxo_yform/issues/1284

Die Klasase `table-responsive` (https://github.com/FriendsOfREDAXO/yform_usability/blob/d843a1b9a6d34fc544169e983f067e3a6091a3e9/lib/Extensions.php#L214) setzt einen overflow der das Action-Button-Dropdown anschneidet.

**Comment by eaCe** [comment]
Würde `overflow-x: auto:` statt der table-responsive Klasse eventuell genügen?

**Comment by alxndr-w** [comment]
Das ist ja genau das, was .table-responsive da macht. Lässt man overflow horizontal nicht zu, geht's halt auch nicht mehr in die vertikale.

```
.table-responsive {
    padding-bottom: 120px;
}
```

<- Das CSS Hilft. Ich glaube, eine bessere Lösung gibt es nicht, da das responsive-table-Konzept in Bootstrap 3 nicht ganz wasserdicht ist.

Generell wäre es wünschenswerter, die Spalten leichter formatieren zu können und ggf. einen Datensatz mehrzeilig darzustellen. Alles andere ist eine Krücke,

**Comment by eaCe** [comment]
@alxndr-w du hast Recht. Ist nicht schön, funktioniert aber. Zumindest solange man keine weiteren Buttons in den Funktionen nutzt.

**Comment by skerbis** [comment]
folgendes hat bei mir geholfen: 

```css
@media (max-width: 767px) {
    .table-responsive .dropdown-menu {
        position: static !important;
    }
}
@media (min-width: 768px) {
    .table-responsive {
        overflow: inherit;
    }
}
```
